### ISSUE TITLE
No OpenIDConnect provider found in your account

### ISSUE THREAD

**Issue by micksabox** [tedivm/action-ecr-publish#8]
Kept getting the error `Error: No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com.`

Noticed the version used for `configure-aws-credentials` is `master`. When I used `configure-aws-credentials@v1` instead, the error went away.

Thanks for the blog post and action, helped me get setup quickly.

**Comment by tedivm** [comment]
Thanks for letting me know! I've released a new version that resolves the issue.
